---
title: "Health vs. Income"
author: "Yiyun Gong"
output: html_notebook
---

```{r}
# always clean up R environment
rm(list = ls())

# load all packages here
library(dplyr)
# load dataset
health_allPop<-
  read.csv("Health_allPop.csv", header = T)
health_percapita<-
  read.csv("Health_percapita.csv", header = T)
income<-
  read.csv("income.csv", header = T)
income_num<-
  read.csv("income_num.csv", header = T)
# user-defined function
remove_comma<-
  function(table_name){
    ncol<-
      ncol(table_name)
    for (i in 2:ncol){
      table_name[,i]<-
        gsub(",","",table_name[,i])
      table_name[,i]<-
        as.numeric(table_name[,i])
    }
    return(table_name)
}
```

#Data Wrangling

###Data Clearing income_num dataset
```{r}
income_num$Year<-
  substr(income_num$Year, 1, 4)
```

```{r}
income_num<-
  remove_comma(income_num)
```

#subsetting and merging datasets income_num and health_percapita
```{r}
income_num$Year<-
  as.numeric(income_num$Year)
income_num_sub<-
  income_num %>%
  filter(Year>1999&Year<2016)%>%
  arrange(Year)
```

```{r}
health_percapita_sub<-
  health_percapita[,1:2]
health_percapita_sub<-
  remove_comma(health_percapita_sub)
```

```{r}
income_num_sub_3fifth<-
  data.frame(income_num_sub[,c(1,4)])
```

#join 60%income with average insurane price per capita
```{r}
insurance_income<-
  merge(x=income_num_sub_3fifth, y=health_percapita_sub, by = "Year", all=TRUE)
```

#Data Visualization



#Data Analysis

